# @no-reject-unauthorized
@webapi_HostAddress = https://localhost:7082

@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXJvbmUiLCJzdWIiOiJ1c2Vyb25lIiwianRpIjoiMjU2ZGIyMyIsInNjb3BlIjoiYWNjZXNzX2FzX3VzZXIiLCJyb2xlIjoidXNlciIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjU5Nzc2IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMjQiLCJodHRwczovL2xvY2FsaG9zdDo3MDgyIiwiaHR0cDovL2xvY2FsaG9zdDo1MTkzIl0sIm5iZiI6MTcxNzQ1ODI1MiwiZXhwIjoxNzI1NDA3MDUyLCJpYXQiOjE3MTc0NTgyNTIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.X8Oc3LJn8ho78cwCResUDy7BrELMdL77PAiB7s4KmNw"

GET {{webapi_HostAddress}}/weatherforecast/
Authorization: Bearer {{TOKEN_ONE}}
Accept: application/json

###
